package com.runecarddungeon.ui;

import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.util.Duration;

/*
* Fire Worm a 51x41 pixels animated scale character with 9 sheets sprites

* Fire ball 19x11 pixels
*/

public class FireBallAni {
	// fire balls movement ( fire balls generated by fire worm)
    private final ImageView imageView;
    private final ModelAnimation moveAnim;
    private final ModelAnimation explodeAnim;
    private ModelAnimation currentAnim;
    
    public FireBallAni() {
        this.imageView = new ImageView();
        
        this.moveAnim    = new ModelAnimation(this.imageView, Duration.millis(400), 6, 19, 11);
        this.explodeAnim = new ModelAnimation(this.imageView, Duration.millis(500), 7, 19, 11);
    }
    
    public void playMove() {
        this.imageView.setImage(new Image("file:assets/Fire_worm/Fire Ball/Move.png"));
        if(currentAnim != null) {
            currentAnim.stop();
        }
        currentAnim = moveAnim;
        // Keep showing the animation during flight
        currentAnim.setCycleCount(ModelAnimation.INDEFINITE);
        currentAnim.setOnFinished(null); // Clear any previous callbacks
        currentAnim.play();
    }
    
    public void playExplode() {
        this.playExplode(null);
    }

    /**
     * Plays the explosion animation with a specific callback.
     * onExplodeFinished the logic executed after the explosion ends
     */
    public void playExplode(Runnable onExplodeFinished) {
        this.imageView.setImage(new Image("file:assets/Fire_worm/Fire Ball/Explosion.png"));
        if(currentAnim != null) {
            currentAnim.stop();
        }
        currentAnim = explodeAnim;
        currentAnim.setCycleCount(1);
        
        if (onExplodeFinished != null) {
            currentAnim.setOnFinished(e -> onExplodeFinished.run());
        } else {
            currentAnim.setOnFinished(null);
        }
        
        currentAnim.play();
    }
    
    public ImageView getImageView() {
        return this.imageView;
    }
}